theme: jekyll-theme-slate

author: khmaker
email: khmaker@yandex.ru
description: no discription

# social links
github_username: khmaker # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
